name: OWASP Dependency Check Pipeline

# This tells GitHub to run the scan every time code is pushed
on:
  push:
    branches: [ "main", "devsecops-setup1" , "test/dependency-check" ] 
  pull_request:
    branches: [ "main", "devsecops-setup1" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Create report directory
      - name: Create Report Directory
        run: mkdir -p odc-reports

      # 2. Run OWASP Dependency-Check via Docker
      - name: Run OWASP Dependency-Check
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            -v ${{ github.workspace }}/odc-reports:/report \
            owasp/dependency-check:latest \
            --project "HPE-CPP3-TEAM-4-CTFd" \
            --scan /src \
            --format HTML \
            --out /report/dependency-check-report.html \
            --enableExperimental \
            --noDdUpdate
        continue-on-error: true

      # 3. Upload the HTML report as a downloadable artifact
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: OWASP-Dependency-Check-Report
          path: odc-reports/dependency-check-report.html